### ISSUE TITLE
[feat] 마이페이지 프로필 내용 UI 구현

### ISSUE THREAD

**Issue by Fiddich-Dev** [spon-us/SponUs-iOS-Sprint2#12]
## 🍏 About
* 프로필 내용 UI 구현

## 🍀 Branch Name
feat/#12-EditProfileVIew-UI

## 🌱 To do
- [ ] 뷰모델
- [ ] 이미지 첨부
- [ ] UI

**Comment by 00yhsp** [comment]
프로필 피그마 홈에 있는 부분까지는 제가 할게용
